//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePara
    {
        public string Company { get; set; }
        public short TwoDay { get; set; }
        public bool NoClockIn { get; set; }
        public bool NoClockOut { get; set; }
        public short LateTime { get; set; }
        public short LeaveTime { get; set; }
        public bool ISOverTime { get; set; }
        public short OverTime { get; set; }
        public short WorkDayLong { get; set; }
        public Nullable<decimal> WOverTime { get; set; }
        public Nullable<decimal> HOverTime { get; set; }
        public Nullable<decimal> FOverTime { get; set; }
        public Nullable<bool> IsAutoDownRec { get; set; }
        public string DownRecTime { get; set; }
        public Nullable<short> OvertimeIn { get; set; }
        public Nullable<bool> IsovertimeIn { get; set; }
        public Nullable<bool> DeductIn { get; set; }
        public Nullable<bool> DeductOut { get; set; }
    }
}
