//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckLog
    {
        public int Logid { get; set; }
        public string Userid { get; set; }
        public System.DateTime Checktime { get; set; }
        public string Checktype { get; set; }
        public string Sensorid { get; set; }
        public Nullable<short> OPFlag { get; set; }
        public string Whys { get; set; }
        public string OPname { get; set; }
        public System.DateTime DTime { get; set; }
    }
}
