//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerClient
    {
        public string Clientid { get; set; }
        public Nullable<short> Linkmode { get; set; }
        public string IPaddress { get; set; }
        public string ClientName { get; set; }
        public string ClientNumber { get; set; }
        public Nullable<int> Baudrate { get; set; }
        public Nullable<int> RecStatus { get; set; }
        public Nullable<int> Floorid { get; set; }
        public Nullable<int> MachineType { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string CommPWD { get; set; }
        public Nullable<int> CommPort { get; set; }
    }
}
