//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holidayid { get; set; }
        public string Name { get; set; }
        public System.DateTime BDate { get; set; }
        public short Days { get; set; }
    }
}
