//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveClass
    {
        public int Classid { get; set; }
        public string Classname { get; set; }
        public int ViewColor { get; set; }
        public string Showas { get; set; }
    }
}
