//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemStat
    {
        public int Lsh { get; set; }
        public string Userid { get; set; }
        public string Udept { get; set; }
        public string Uname { get; set; }
        public float Normal { get; set; }
        public float Actual { get; set; }
        public float Latetime { get; set; }
        public float Earlytime { get; set; }
        public float Absenttime { get; set; }
        public float Overtime { get; set; }
        public int Noin { get; set; }
        public int Noout { get; set; }
        public float Awaytime { get; set; }
        public float BLeave { get; set; }
        public float Leave { get; set; }
        public float Freeovertime { get; set; }
        public float Worktime { get; set; }
        public float Attrate { get; set; }
    }
}
