//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPLog
    {
        public int Logid { get; set; }
        public int OPid { get; set; }
        public System.DateTime Optime { get; set; }
        public string OPlog1 { get; set; }
    }
}
