//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schid { get; set; }
        public string Schname { get; set; }
        public short Cycles { get; set; }
        public short Units { get; set; }
        public Nullable<bool> AutoClass { get; set; }
    }
}
