//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Checkinout
    {
        public int Logid { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckType { get; set; }
        public string Sensorid { get; set; }
        public bool Checked { get; set; }
        public int WorkType { get; set; }
        public int AttFlag { get; set; }
    }
}
