//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShift
    {
        public string Userid { get; set; }
        public int Schid { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
    }
}
