//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCtrLog
    {
        public int Logid { get; set; }
        public string Clientid { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string ULog { get; set; }
    }
}
