//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserinfoBackup
    {
        public string Userid { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> Deptid { get; set; }
        public string Nation { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public Nullable<System.DateTime> EmployDate { get; set; }
        public string Telephone { get; set; }
        public string Duty { get; set; }
        public string NativePlace { get; set; }
        public string IDCard { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Educated { get; set; }
        public string Polity { get; set; }
        public string Specialty { get; set; }
        public bool IsAtt { get; set; }
        public bool Isovertime { get; set; }
        public bool Isrest { get; set; }
        public string Remark { get; set; }
        public Nullable<short> MgFlag { get; set; }
        public string Cardnum { get; set; }
        public string Machineid { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> UserFlag { get; set; }
        public Nullable<int> Groupid { get; set; }
        public Nullable<int> workdaylong { get; set; }
    }
}
