//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Class
    {
        public int Schid { get; set; }
        public string Schname { get; set; }
        public short Cycles { get; set; }
        public short Units { get; set; }
        public Nullable<bool> AutoClass { get; set; }
        public short BeginDay { get; set; }
        public int Timeid { get; set; }
        public string Timename { get; set; }
        public string Intime { get; set; }
        public string Outtime { get; set; }
        public string BIntime { get; set; }
        public string EIntime { get; set; }
        public string BOuttime { get; set; }
        public string EOuttime { get; set; }
        public short Latetime { get; set; }
        public short Leavetime { get; set; }
        public decimal WorkDays { get; set; }
        public short Longtime { get; set; }
        public Nullable<bool> MustIn { get; set; }
        public Nullable<bool> MustOut { get; set; }
        public Nullable<bool> IsFreetime { get; set; }
        public Nullable<bool> IsOvertime { get; set; }
    }
}
