//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserClient
    {
        public int Logid { get; set; }
        public string Userid { get; set; }
        public string ClientNumber { get; set; }
        public int PowerFlag { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public string CardNum { get; set; }
        public int Deptid { get; set; }
        public Nullable<int> UserFlag { get; set; }
        public Nullable<short> MgFlag { get; set; }
        public Nullable<int> Groupid { get; set; }
    }
}
